name: Build on Commit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - name: Build protobuf & Nuget restore
      run: |
        protoc -I"SakuraLibrary\Proto" SakuraLibrary\Proto\*.proto --csharp_out=SakuraLibrary\Proto\Out
        nuget restore
        
    - name: Build the project
      run: msbuild SakuraLauncher.sln -t:rebuild -property:Configuration=Debug
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DebugBuild
        path: bin/Debug

